#include <iostream>
#include <iomanip>
#include "Vstopwatch_top.h" // Header generated by Verilator
#include "verilated.h"

// Define the simulation time variable
vluint64_t main_time = 0;

// Helper function to simulate one clock cycle
void tick(Vstopwatch_top* top) {
    // Toggle Clock Low
    top->clk = 0;
    top->eval(); // Update the model
    
    // Toggle Clock High
    top->clk = 1;
    top->eval(); // Update the model again
    
    main_time++;
}

int main(int argc, char** argv) {
    // Initialize Verilator
    Verilated::commandArgs(argc, argv);
    
    // Create an instance of our module
    Vstopwatch_top* top = new Vstopwatch_top;

    std::cout << "Starting Simulation..." << std::endl;

    // --- 1. System Reset ---
    top->rst_n = 0; // Assert Reset
    top->start = 0;
    top->stop = 0;
    top->reset = 0;
    
    // Run for a few cycles in reset
    for(int i = 0; i < 5; i++) tick(top);
    
    top->rst_n = 1; // Release Reset
    std::cout << "Reset Complete." << std::endl;

    // --- 2. Start the Stopwatch ---
    std::cout << "Command: START" << std::endl;
    top->start = 1;
    tick(top);
    top->start = 0; // Release button (single cycle pulse)

    // Let it run for 70 seconds (approx 70 clock cycles for this simple model)
    // Note: In real hardware, 1 second = millions of clocks. 
    // Here we assume 1 clock = 1 second for fast simulation visualization.
    for (int i = 0; i < 70; i++) {
        tick(top);
        // Print time every 10 ticks
        if (i % 10 == 0) {
            std::cout << "Time: " 
                      << std::setw(2) << std::setfill('0') << (int)top->minutes << ":"
                      << std::setw(2) << std::setfill('0') << (int)top->seconds 
                      << " [RUNNING]" << std::endl;
        }
    }

    // --- 3. Stop (Pause) ---
    std::cout << "Command: STOP (Pause)" << std::endl;
    top->stop = 1;
    tick(top);
    top->stop = 0;

    // Verify it is paused (run 5 ticks, time shouldn't change)
    for (int i = 0; i < 5; i++) {
        tick(top);
        std::cout << "Time: " 
                  << std::setw(2) << std::setfill('0') << (int)top->minutes << ":"
                  << std::setw(2) << std::setfill('0') << (int)top->seconds 
                  << " [PAUSED]" << std::endl;
    }

    // --- 4. Resume ---
    std::cout << "Command: RESUME" << std::endl;
    top->start = 1;
    tick(top);
    top->start = 0;

    // Run for 5 more seconds
    for (int i = 0; i < 5; i++) tick(top);
    
    std::cout << "Final Time: " 
              << std::setw(2) << std::setfill('0') << (int)top->minutes << ":"
              << std::setw(2) << std::setfill('0') << (int)top->seconds 
              << std::endl;

    // Clean up
    delete top;
    return 0;
}